/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as RecorrentesRouteImport } from './routes/recorrentes'
import { Route as MetasRouteImport } from './routes/metas'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as InvestimentosRouteImport } from './routes/investimentos'
import { Route as FinanceiroRouteImport } from './routes/financeiro'
import { Route as FgtsRouteImport } from './routes/fgts'
import { Route as FaturasRouteImport } from './routes/faturas'
import { Route as ExtratosRouteImport } from './routes/extratos'
import { Route as DividasRouteImport } from './routes/dividas'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as CartoesRouteImport } from './routes/cartoes'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as ImportReviewIdRouteImport } from './routes/import.review.$id'
import { Route as ApiImportExtratoRouteImport } from './routes/api/import.extrato'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const RecorrentesRoute = RecorrentesRouteImport.update({
  id: '/recorrentes',
  path: '/recorrentes',
  getParentRoute: () => rootRouteImport,
} as any)
const MetasRoute = MetasRouteImport.update({
  id: '/metas',
  path: '/metas',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestimentosRoute = InvestimentosRouteImport.update({
  id: '/investimentos',
  path: '/investimentos',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceiroRoute = FinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => rootRouteImport,
} as any)
const FgtsRoute = FgtsRouteImport.update({
  id: '/fgts',
  path: '/fgts',
  getParentRoute: () => rootRouteImport,
} as any)
const FaturasRoute = FaturasRouteImport.update({
  id: '/faturas',
  path: '/faturas',
  getParentRoute: () => rootRouteImport,
} as any)
const ExtratosRoute = ExtratosRouteImport.update({
  id: '/extratos',
  path: '/extratos',
  getParentRoute: () => rootRouteImport,
} as any)
const DividasRoute = DividasRouteImport.update({
  id: '/dividas',
  path: '/dividas',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const CartoesRoute = CartoesRouteImport.update({
  id: '/cartoes',
  path: '/cartoes',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const ImportReviewIdRoute = ImportReviewIdRouteImport.update({
  id: '/import/review/$id',
  path: '/import/review/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiImportExtratoRoute = ApiImportExtratoRouteImport.update({
  id: '/api/import/extrato',
  path: '/api/import/extrato',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cartoes': typeof CartoesRoute
  '/chat': typeof ChatRoute
  '/dividas': typeof DividasRoute
  '/extratos': typeof ExtratosRoute
  '/faturas': typeof FaturasRoute
  '/fgts': typeof FgtsRoute
  '/financeiro': typeof FinanceiroRoute
  '/investimentos': typeof InvestimentosRoute
  '/mcp': typeof McpRoute
  '/metas': typeof MetasRoute
  '/recorrentes': typeof RecorrentesRoute
  '/relatorios': typeof RelatoriosRoute
  '/settings': typeof SettingsRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/import/extrato': typeof ApiImportExtratoRoute
  '/import/review/$id': typeof ImportReviewIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cartoes': typeof CartoesRoute
  '/chat': typeof ChatRoute
  '/dividas': typeof DividasRoute
  '/extratos': typeof ExtratosRoute
  '/faturas': typeof FaturasRoute
  '/fgts': typeof FgtsRoute
  '/financeiro': typeof FinanceiroRoute
  '/investimentos': typeof InvestimentosRoute
  '/mcp': typeof McpRoute
  '/metas': typeof MetasRoute
  '/recorrentes': typeof RecorrentesRoute
  '/relatorios': typeof RelatoriosRoute
  '/settings': typeof SettingsRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/import/extrato': typeof ApiImportExtratoRoute
  '/import/review/$id': typeof ImportReviewIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cartoes': typeof CartoesRoute
  '/chat': typeof ChatRoute
  '/dividas': typeof DividasRoute
  '/extratos': typeof ExtratosRoute
  '/faturas': typeof FaturasRoute
  '/fgts': typeof FgtsRoute
  '/financeiro': typeof FinanceiroRoute
  '/investimentos': typeof InvestimentosRoute
  '/mcp': typeof McpRoute
  '/metas': typeof MetasRoute
  '/recorrentes': typeof RecorrentesRoute
  '/relatorios': typeof RelatoriosRoute
  '/settings': typeof SettingsRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/import/extrato': typeof ApiImportExtratoRoute
  '/import/review/$id': typeof ImportReviewIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/cartoes'
    | '/chat'
    | '/dividas'
    | '/extratos'
    | '/faturas'
    | '/fgts'
    | '/financeiro'
    | '/investimentos'
    | '/mcp'
    | '/metas'
    | '/recorrentes'
    | '/relatorios'
    | '/settings'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/api/import/extrato'
    | '/import/review/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/cartoes'
    | '/chat'
    | '/dividas'
    | '/extratos'
    | '/faturas'
    | '/fgts'
    | '/financeiro'
    | '/investimentos'
    | '/mcp'
    | '/metas'
    | '/recorrentes'
    | '/relatorios'
    | '/settings'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/api/import/extrato'
    | '/import/review/$id'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/cartoes'
    | '/chat'
    | '/dividas'
    | '/extratos'
    | '/faturas'
    | '/fgts'
    | '/financeiro'
    | '/investimentos'
    | '/mcp'
    | '/metas'
    | '/recorrentes'
    | '/relatorios'
    | '/settings'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/api/import/extrato'
    | '/import/review/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  CartoesRoute: typeof CartoesRoute
  ChatRoute: typeof ChatRoute
  DividasRoute: typeof DividasRoute
  ExtratosRoute: typeof ExtratosRoute
  FaturasRoute: typeof FaturasRoute
  FgtsRoute: typeof FgtsRoute
  FinanceiroRoute: typeof FinanceiroRoute
  InvestimentosRoute: typeof InvestimentosRoute
  McpRoute: typeof McpRoute
  MetasRoute: typeof MetasRoute
  RecorrentesRoute: typeof RecorrentesRoute
  RelatoriosRoute: typeof RelatoriosRoute
  SettingsRoute: typeof SettingsRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiImportExtratoRoute: typeof ApiImportExtratoRoute
  ImportReviewIdRoute: typeof ImportReviewIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recorrentes': {
      id: '/recorrentes'
      path: '/recorrentes'
      fullPath: '/recorrentes'
      preLoaderRoute: typeof RecorrentesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metas': {
      id: '/metas'
      path: '/metas'
      fullPath: '/metas'
      preLoaderRoute: typeof MetasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investimentos': {
      id: '/investimentos'
      path: '/investimentos'
      fullPath: '/investimentos'
      preLoaderRoute: typeof InvestimentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financeiro': {
      id: '/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof FinanceiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fgts': {
      id: '/fgts'
      path: '/fgts'
      fullPath: '/fgts'
      preLoaderRoute: typeof FgtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faturas': {
      id: '/faturas'
      path: '/faturas'
      fullPath: '/faturas'
      preLoaderRoute: typeof FaturasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/extratos': {
      id: '/extratos'
      path: '/extratos'
      fullPath: '/extratos'
      preLoaderRoute: typeof ExtratosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dividas': {
      id: '/dividas'
      path: '/dividas'
      fullPath: '/dividas'
      preLoaderRoute: typeof DividasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cartoes': {
      id: '/cartoes'
      path: '/cartoes'
      fullPath: '/cartoes'
      preLoaderRoute: typeof CartoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import/review/$id': {
      id: '/import/review/$id'
      path: '/import/review/$id'
      fullPath: '/import/review/$id'
      preLoaderRoute: typeof ImportReviewIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/import/extrato': {
      id: '/api/import/extrato'
      path: '/api/import/extrato'
      fullPath: '/api/import/extrato'
      preLoaderRoute: typeof ApiImportExtratoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  CartoesRoute: CartoesRoute,
  ChatRoute: ChatRoute,
  DividasRoute: DividasRoute,
  ExtratosRoute: ExtratosRoute,
  FaturasRoute: FaturasRoute,
  FgtsRoute: FgtsRoute,
  FinanceiroRoute: FinanceiroRoute,
  InvestimentosRoute: InvestimentosRoute,
  McpRoute: McpRoute,
  MetasRoute: MetasRoute,
  RecorrentesRoute: RecorrentesRoute,
  RelatoriosRoute: RelatoriosRoute,
  SettingsRoute: SettingsRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiImportExtratoRoute: ApiImportExtratoRoute,
  ImportReviewIdRoute: ImportReviewIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
