/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as RecorrentesRouteImport } from './routes/recorrentes'
import { Route as MetasRouteImport } from './routes/metas'
import { Route as InvestimentosRouteImport } from './routes/investimentos'
import { Route as FinanceiroRouteImport } from './routes/financeiro'
import { Route as FgtsRouteImport } from './routes/fgts'
import { Route as FaturasRouteImport } from './routes/faturas'
import { Route as ExtratosRouteImport } from './routes/extratos'
import { Route as DividasRouteImport } from './routes/dividas'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as CartoesRouteImport } from './routes/cartoes'
import { Route as IndexRouteImport } from './routes/index'

const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const RecorrentesRoute = RecorrentesRouteImport.update({
  id: '/recorrentes',
  path: '/recorrentes',
  getParentRoute: () => rootRouteImport,
} as any)
const MetasRoute = MetasRouteImport.update({
  id: '/metas',
  path: '/metas',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestimentosRoute = InvestimentosRouteImport.update({
  id: '/investimentos',
  path: '/investimentos',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceiroRoute = FinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => rootRouteImport,
} as any)
const FgtsRoute = FgtsRouteImport.update({
  id: '/fgts',
  path: '/fgts',
  getParentRoute: () => rootRouteImport,
} as any)
const FaturasRoute = FaturasRouteImport.update({
  id: '/faturas',
  path: '/faturas',
  getParentRoute: () => rootRouteImport,
} as any)
const ExtratosRoute = ExtratosRouteImport.update({
  id: '/extratos',
  path: '/extratos',
  getParentRoute: () => rootRouteImport,
} as any)
const DividasRoute = DividasRouteImport.update({
  id: '/dividas',
  path: '/dividas',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const CartoesRoute = CartoesRouteImport.update({
  id: '/cartoes',
  path: '/cartoes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cartoes': typeof CartoesRoute
  '/chat': typeof ChatRoute
  '/dividas': typeof DividasRoute
  '/extratos': typeof ExtratosRoute
  '/faturas': typeof FaturasRoute
  '/fgts': typeof FgtsRoute
  '/financeiro': typeof FinanceiroRoute
  '/investimentos': typeof InvestimentosRoute
  '/metas': typeof MetasRoute
  '/recorrentes': typeof RecorrentesRoute
  '/relatorios': typeof RelatoriosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cartoes': typeof CartoesRoute
  '/chat': typeof ChatRoute
  '/dividas': typeof DividasRoute
  '/extratos': typeof ExtratosRoute
  '/faturas': typeof FaturasRoute
  '/fgts': typeof FgtsRoute
  '/financeiro': typeof FinanceiroRoute
  '/investimentos': typeof InvestimentosRoute
  '/metas': typeof MetasRoute
  '/recorrentes': typeof RecorrentesRoute
  '/relatorios': typeof RelatoriosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cartoes': typeof CartoesRoute
  '/chat': typeof ChatRoute
  '/dividas': typeof DividasRoute
  '/extratos': typeof ExtratosRoute
  '/faturas': typeof FaturasRoute
  '/fgts': typeof FgtsRoute
  '/financeiro': typeof FinanceiroRoute
  '/investimentos': typeof InvestimentosRoute
  '/metas': typeof MetasRoute
  '/recorrentes': typeof RecorrentesRoute
  '/relatorios': typeof RelatoriosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cartoes'
    | '/chat'
    | '/dividas'
    | '/extratos'
    | '/faturas'
    | '/fgts'
    | '/financeiro'
    | '/investimentos'
    | '/metas'
    | '/recorrentes'
    | '/relatorios'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cartoes'
    | '/chat'
    | '/dividas'
    | '/extratos'
    | '/faturas'
    | '/fgts'
    | '/financeiro'
    | '/investimentos'
    | '/metas'
    | '/recorrentes'
    | '/relatorios'
  id:
    | '__root__'
    | '/'
    | '/cartoes'
    | '/chat'
    | '/dividas'
    | '/extratos'
    | '/faturas'
    | '/fgts'
    | '/financeiro'
    | '/investimentos'
    | '/metas'
    | '/recorrentes'
    | '/relatorios'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CartoesRoute: typeof CartoesRoute
  ChatRoute: typeof ChatRoute
  DividasRoute: typeof DividasRoute
  ExtratosRoute: typeof ExtratosRoute
  FaturasRoute: typeof FaturasRoute
  FgtsRoute: typeof FgtsRoute
  FinanceiroRoute: typeof FinanceiroRoute
  InvestimentosRoute: typeof InvestimentosRoute
  MetasRoute: typeof MetasRoute
  RecorrentesRoute: typeof RecorrentesRoute
  RelatoriosRoute: typeof RelatoriosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recorrentes': {
      id: '/recorrentes'
      path: '/recorrentes'
      fullPath: '/recorrentes'
      preLoaderRoute: typeof RecorrentesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metas': {
      id: '/metas'
      path: '/metas'
      fullPath: '/metas'
      preLoaderRoute: typeof MetasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investimentos': {
      id: '/investimentos'
      path: '/investimentos'
      fullPath: '/investimentos'
      preLoaderRoute: typeof InvestimentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financeiro': {
      id: '/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof FinanceiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fgts': {
      id: '/fgts'
      path: '/fgts'
      fullPath: '/fgts'
      preLoaderRoute: typeof FgtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faturas': {
      id: '/faturas'
      path: '/faturas'
      fullPath: '/faturas'
      preLoaderRoute: typeof FaturasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/extratos': {
      id: '/extratos'
      path: '/extratos'
      fullPath: '/extratos'
      preLoaderRoute: typeof ExtratosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dividas': {
      id: '/dividas'
      path: '/dividas'
      fullPath: '/dividas'
      preLoaderRoute: typeof DividasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cartoes': {
      id: '/cartoes'
      path: '/cartoes'
      fullPath: '/cartoes'
      preLoaderRoute: typeof CartoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CartoesRoute: CartoesRoute,
  ChatRoute: ChatRoute,
  DividasRoute: DividasRoute,
  ExtratosRoute: ExtratosRoute,
  FaturasRoute: FaturasRoute,
  FgtsRoute: FgtsRoute,
  FinanceiroRoute: FinanceiroRoute,
  InvestimentosRoute: InvestimentosRoute,
  MetasRoute: MetasRoute,
  RecorrentesRoute: RecorrentesRoute,
  RelatoriosRoute: RelatoriosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
